[package]
name        = "darwin-metrics"
version     = "0.1.0"
edition     = "2024"
description = "A Rust library exposing native macOS system metrics"
authors     = ["Stuart Meya <sm0sh1@pm.me>"]
license     = "MIT"
repository  = "https://github.com/sm-moshi/darwin-metrics"
keywords    = ["macos", "system", "metrics", "ffi", "swift"]
categories  = ["os", "api-bindings"]
readme      = "README.md"

[lib]
name       = "darwin_metrics"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
# Core FFI and system interfaces
swift-bridge    = "0.1.57"
libc            = "0.2.170"
core-foundation = "0.10.0"
objc            = "0.2.7"
mach-sys        = "0.5.4"
io-kit-sys      = "0.4.1"

# Async support
tokio   = { version = "1.43.0", features = ["full"], optional = true }
futures = "0.3.31"

# Error handling and logging
thiserror          = "2.0.11"
tracing            = { version = "0.1.41", features = ["attributes"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

# Serialization and data handling
serde      = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"

# Metrics and monitoring
metrics-runtime = { version = "0.13.1", optional = true }
cached          = { version = "0.54.0", optional = true }

[build-dependencies]
swift-bridge-build = "0.1.57"

[dev-dependencies]
criterion        = "0.5.1"
assert_approx_eq = "1.1.0"
tokio-test       = "0.4.4"
test-log         = "0.2.17"
mockall          = "0.13.1"

[features]
default = ["battery", "cpu", "memory", "gpu", "disk", "temperature", "async"]

# Core features
battery            = []
cpu                = []
memory             = []
gpu                = []
disk               = []
temperature        = []
process_monitoring = []

# Optional features
async          = ["tokio"]
metrics-export = ["metrics-runtime"]
cached-metrics = ["cached"]

[[bench]]
name    = "darwin-metrics"
harness = false

[profile.release]
lto           = true
codegen-units = 1
opt-level     = 3
debug         = false
strip         = true

[profile.dev]
opt-level = 0
debug     = true

[package.metadata]
docs.rs.all-features = true
