[package]
name = "darwin-metrics"
version = "0.0.1"
edition = "2021"
description = "A Rust library exposing native macOS system metrics"
authors = ["Stuart Meya <sm0sh1@pm.me>"]
license = "MIT"
repository = "https://github.com/sm-moshi/darwin-metrics"
keywords = ["macos", "system", "metrics", "ffi", "swift"]
categories = ["os", "api-bindings"]
readme = "README.md"
links = "darwin_metrics"

[lib]
name = "darwin_metrics"
crate-type = ["rlib", "cdylib", "staticlib"]

[build-dependencies]
cc = "1.2.16"

[dependencies]
# Core FFI and system interfaces
libc = "0.2.170"
libproc = "0.14.10"
objc2 = { version = "0.6.0", features = [
  "alloc",
  "objc2-proc-macros",
  "std",
  "exception",
  "catch-all",
] }
objc2-foundation = "0.3.0"
objc2-core-foundation = "0.3.0"
objc2-core-graphics = "0.3.0"
block2 = { version = "0.6.0", features = ["alloc", "std"] }
scopeguard = "1.2.0"

# Error handling and logging
tokio = { version = "1.44.0", features = ["full"] }
futures = "0.3.31"
futures-util = "0.3.31"
async-trait = "0.1.87"
thiserror = "2.0.12"
tracing = { version = "0.1.41", features = ["attributes"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

# Serialization and data handling
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"

# Metrics and monitoring
metrics-runtime = { version = "0.13.1", optional = true }
cached = { version = "0.55.1", optional = true }

# Testing
proptest = { version = "1.6.0", optional = true }
mockall = "0.13.1"
test-log = { version = "0.2.17", optional = true }

# Additional dependencies
parking_lot = "0.12.3"
lazy_static = "1.5.0"
log = "0.4.26"
once_cell = "1.20.3"

[dev-dependencies]
tokio-test = "0.4.4"

[features]
default = ["battery", "cpu", "memory", "gpu", "disk", "temperature", "async"]

# Core features
battery = []
cpu = []
memory = []
gpu = []
disk = []
temperature = []
process_monitoring = []

# Optional features
async = []
metrics-export = ["metrics-runtime"]
cached-metrics = ["cached"]

# Testing features
unstable-tests = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = false
strip = true

[profile.dev]
opt-level = 0
debug = true

# Documentation configuration for docs.rs
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = ["x86_64-apple-darwin", "aarch64-apple-darwin"]
default-target = "aarch64-apple-darwin"
rustc-args = ["--cfg", "docs_rs"]

[package.metadata]
minimum-macos-version = "10.11"

[package.metadata.llvm-cov]
enable = ["line", "branch", "function", "mcdc"]
threshold = 80
exclude = ["tests/*", "target/*", "**/*_test.rs"]
