# Basic formatting options
edition              = "2024"
max_width            = 120
tab_spaces           = 4
hard_tabs            = false
newline_style        = "Unix"
use_small_heuristics = "Default"

# Import formatting
reorder_imports     = true
imports_granularity = "Module"
group_imports       = "StdExternalCrate"

# Code organization
reorder_modules            = true
match_block_trailing_comma = true
use_field_init_shorthand   = true
use_try_shorthand          = true
merge_derives              = true

# Additional formatting
format_strings        = true
format_macro_matchers = true
format_macro_bodies   = true
normalize_comments    = true
