# Basic formatting options
edition              = "2024"
max_width            = 100
tab_spaces           = 4
hard_tabs            = false
newline_style        = "Unix"
use_small_heuristics = "Max"

# Import formatting
imports_granularity = "Crate"
group_imports       = "StdExternalCrate"
reorder_imports     = true

# Code organization
reorder_modules            = true
match_block_trailing_comma = true
use_field_init_shorthand   = true
use_try_shorthand          = true

# Documentation formatting
wrap_comments                = true
format_code_in_doc_comments  = true
doc_comment_code_block_width = 120

# Specific to Rust Async Development
format_macro_matchers = true
format_macro_bodies   = true
format_strings        = true
