// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$TestFFI { int32_t value; double other_value; } __swift_bridge__$TestFFI;
typedef struct __swift_bridge__$Option$TestFFI { bool is_some; __swift_bridge__$TestFFI val; } __swift_bridge__$Option$TestFFI;
typedef struct __swift_bridge__$TestFFIResult { bool success; struct __swift_bridge__$TestFFI data; } __swift_bridge__$TestFFIResult;
typedef struct __swift_bridge__$Option$TestFFIResult { bool is_some; __swift_bridge__$TestFFIResult val; } __swift_bridge__$Option$TestFFIResult;


