[env]
LLVM_PROFILE_FILE = "coverage/default_%p_%m.profraw"

[target.'cfg(unix)']
rustflags = ["-C", "instrument-coverage=all", "-C", "link-dead-code"]

[llvm-cov]
output-dir = "coverage"
output-path = "coverage/lcov.info"
