[env]
LLVM_PROFILE_FILE = "coverage/default_%p_%m.profraw"

[target.'cfg(unix)']
rustflags = ["-C", "instrument-coverage=all", "-C", "link-dead-code"]

[llvm-cov]
output-dir  = "coverage"
output-path = "coverage/lcov.info"

[test]
# Enable test-utils feature for all test runs
harness   = true
rustflags = ["--cfg", "test", "--cfg", "feature=\"test-utils\""]
