//! This module is only used to make the automock-generated MockIOKit
//! available to tests in other modules.

// Re-export the MockIOKit generated by mockall
pub use crate::hardware::iokit::MockIOKit;
