[book]
title        = "darwin-metrics"
authors      = ["Stuart Meya"]
language     = "en"
multilingual = false
src          = "src"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/sm-moshi/darwin-metrics"
edit-url-template = "https://github.com/sm-moshi/darwin-metrics/edit/main/docs/{path}"
additional-css = ["custom.css"]
default-theme = "light"
preferred-dark-theme = "ayu"

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.playground]
editable = true
line-numbers = true
runnable = false  # Disable runnable examples since darwin-metrics isn't available in the playground

# Skip all tests since we are using example code that relies on darwin-metrics
[test]
command = "echo 'Tests skipped - darwin-metrics is not available'"
fail-on-error = false
