name: Continuous Integration

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main", "0.1.x", "0.2.x"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  CARGO_INCREMENTAL: 0
  CARGO_HTTP_MULTIPLEXING: false

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Setup Rust beta for linting
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: beta
          components: clippy, rustfmt, llvm-tools-preview

      - name: Verify toolchain installation
        run: |
          rustup show
          echo "Installing clippy and rustfmt for beta toolchain if needed"
          rustup component add clippy rustfmt --toolchain beta
          echo "Installed components:"
          rustup +beta component list --installed
      - name: Workaround for curl network errors
        if: ${{ matrix.rust == '1.70.0' || matrix.rust == '1.71.0' }}
        run: echo 'CARGO_HTTP_MULTIPLEXING=false' >> $GITHUB_ENV

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo +beta fmt -- --check

      - name: Check if Clippy is installed
        run: cargo +beta clippy --version || echo "Clippy not installed"

      - name: Clippy
        run: cargo +beta clippy --workspace --all-targets --all-features -- -D warnings -A non_snake_case
        continue-on-error: true

      - name: Build with retry
        run: |
          for i in {1..3}; do cargo +${{ matrix.rust }} build --all-features && break || sleep 10; done
        continue-on-error: true

      - name: Run tests with retry
        run: |
          for i in {1..3}; do cargo +${{ matrix.rust }} test --all-features && break || sleep 10; done
        continue-on-error: true

      - name: Check documentation
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --no-deps --all-features

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path ./coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Clean up .DS_Store files
        run: |
          find . -name ".DS_Store" -type f -delete
          find ./target -name ".DS_Store" -type f -delete 2>/dev/null || true

      - name: Dry run publish
        run: cargo publish --dry-run --no-verify --allow-dirty
