name: Rust (macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust (latest stable)
      uses: dtolnay/rust-toolchain@stable
    - name: Install Xcode Command Line Tools
      run: sudo xcode-select --install || true
    - name: Work around spurious network errors in curl 8.0
      run: |
        if rustc +stable --version --verbose | grep -q '^release: 1\.7[01]\.'; then
          echo "CARGO_HTTP_MULTIPLEXING=false" >> $GITHUB_ENV
        fi
    - name: Build
      run: |
        retry() {
          for i in {1..3}; do
            "$@" && break || sleep 5
          done
        }
        retry cargo build --verbose
    - name: Run tests
      run: |
        retry() {
          for i in {1..3}; do
            "$@" && break || sleep 5
          done
        }
        retry cargo test --verbose
